#!/usr/bin/env bash
set -e

# Build script for HarmonyOS
# Usage: ./build-harmony.sh [debug|release] [--verbose]

BUILD_TYPE="${1:-debug}"
VERBOSE=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --verbose|-v)
            VERBOSE=true
            shift
            ;;
        debug|release)
            BUILD_TYPE="$arg"
            shift
            ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_DIR/harmonyos-build"

echo "========================================="
echo "Building Redis SDK for HarmonyOS"
echo "========================================="
echo "Build type: $BUILD_TYPE"
echo "Verbose: $VERBOSE"
echo "Project dir: $PROJECT_DIR"
echo "Output dir: $OUTPUT_DIR"
echo ""

# Set verbose flags
CARGO_VERBOSE=""
OHRS_VERBOSE=""
if [ "$VERBOSE" = true ]; then
    CARGO_VERBOSE="-v"
    OHRS_VERBOSE="--verbose"
fi

# Check prerequisites
if ! command -v ohrs &> /dev/null; then
    echo "ERROR: ohrs not found. Please install it:"
    echo "  cargo install ohrs"
    exit 1
fi

if [ -z "$OHOS_NDK_HOME" ]; then
    echo "WARNING: OHOS_NDK_HOME not set. Using default from ohrs."
fi

# Clean output directory
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Build targets - only aarch64 for real devices
TARGETS=(
    "aarch64-unknown-linux-ohos"
)

# Map Rust targets to ohrs arch names
declare -A TARGET_MAP_OHRS=(
    ["aarch64-unknown-linux-ohos"]="arm64"
)

# Map Rust targets to HarmonyOS ABI names
declare -A TARGET_MAP_OHOS=(
    ["aarch64-unknown-linux-ohos"]="arm64-v8a"
)

cd "$PROJECT_DIR"

# Determine build profile
if [ "$BUILD_TYPE" = "release" ]; then
    PROFILE="release"
else
    PROFILE="dev"
fi

for TARGET in "${TARGETS[@]}"; do
    echo "----------------------------------------"
    echo "Building for target: $TARGET"
    echo "----------------------------------------"
    
    OHRS_ARCH=${TARGET_MAP_OHRS["$TARGET"]}
    OHOS_ABI=${TARGET_MAP_OHOS["$TARGET"]}
    
    echo "OHRS arch: $OHRS_ARCH"
    echo "HarmonyOS ABI: $OHOS_ABI"
    
    # Build using ohrs
    if [ "$BUILD_TYPE" = "release" ]; then
        if [ "$VERBOSE" = true ]; then
            ohrs build --release --arch="$OHRS_ARCH" $OHRS_VERBOSE
        else
            ohrs build --release --arch="$OHRS_ARCH"
        fi
    else
        if [ "$VERBOSE" = true ]; then
            ohrs build --arch="$OHRS_ARCH" --profile="$PROFILE" $OHRS_VERBOSE
        else
            ohrs build --arch="$OHRS_ARCH" --profile="$PROFILE"
        fi
    fi

    if [ $? -ne 0 ]; then
        echo "ERROR: Build failed for $TARGET"
        exit 1
    fi
    
    # Copy output
    mkdir -p "$OUTPUT_DIR/$OHOS_ABI"

    # Determine the correct target directory (workspace root)
    WORKSPACE_ROOT="$(cd "$PROJECT_DIR/.." && pwd)"

    if [ "$BUILD_TYPE" = "release" ]; then
        LIB_PATH="$WORKSPACE_ROOT/target/$TARGET/release/libredis_ohos.so"
    else
        LIB_PATH="$WORKSPACE_ROOT/target/$TARGET/$PROFILE/libredis_ohos.so"
    fi

    if [ -f "$LIB_PATH" ]; then
        cp "$LIB_PATH" "$OUTPUT_DIR/$OHOS_ABI/"
    else
        echo "ERROR: Library not found at $LIB_PATH"
        exit 1
    fi
    
    echo "✓ Built for $OHOS_ABI"
    echo ""
done

# Copy TypeScript definitions (generated by ohrs in dist/ directory)
if [ -f "dist/index.d.ts" ]; then
    cp "dist/index.d.ts" "$OUTPUT_DIR/"
    echo "✓ Copied TypeScript definitions from dist/"
elif [ "$BUILD_TYPE" = "release" ]; then
    TARGET_DIR="$WORKSPACE_ROOT/target/aarch64-unknown-linux-ohos/release"
    if [ -f "$TARGET_DIR/index.d.ts" ]; then
        cp "$TARGET_DIR/index.d.ts" "$OUTPUT_DIR/"
        echo "✓ Copied TypeScript definitions from target/"
    fi
else
    TARGET_DIR="$WORKSPACE_ROOT/target/aarch64-unknown-linux-ohos/$PROFILE"
    if [ -f "$TARGET_DIR/index.d.ts" ]; then
        cp "$TARGET_DIR/index.d.ts" "$OUTPUT_DIR/"
        echo "✓ Copied TypeScript definitions from target/"
    fi
fi

# Create oh-package.json5
cat > "$OUTPUT_DIR/oh-package.json5" << 'EOF'
{
  "name": "libredis_ohos.so",
  "version": "1.0.0",
  "description": "Redis SDK for HarmonyOS",
  "main": "libredis_ohos.so",
  "author": "Liang"
}
EOF

echo "✓ Created oh-package.json5"
echo ""

echo "========================================="
echo "Build completed successfully!"
echo "========================================="
echo "Output directory: $OUTPUT_DIR"
echo ""
echo "Contents:"
ls -lh "$OUTPUT_DIR"
echo ""
for ABI_DIR in "$OUTPUT_DIR"/*/; do
    if [ -d "$ABI_DIR" ]; then
        ABI_NAME=$(basename "$ABI_DIR")
        echo "$ABI_NAME:"
        ls -lh "$ABI_DIR"
        echo ""
    fi
done

echo "To use in your HarmonyOS project:"
echo "1. Copy $OUTPUT_DIR/* to your project's entry/libs/Redis_sdk/"
echo "2. Add dependency in entry/oh-package.json5:"
echo '   "dependencies": {'
echo '     "libredis_ohos.so": "file:./libs/Redis_sdk"'
echo '   }'
echo ""
echo "For more information, see redis-ohos/README.md"

