#!/usr/bin/env bash
set -e

# Build script for all HarmonyOS targets
# Usage: ./build-all-targets.sh [debug|release]

BUILD_TYPE="${1:-debug}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_DIR/harmonyos-build"
WORKSPACE_ROOT="$(cd "$PROJECT_DIR/.." && pwd)"

echo "========================================="
echo "Building Redis SDK for All HarmonyOS Targets"
echo "========================================="
echo "Build type: $BUILD_TYPE"
echo "Project dir: $PROJECT_DIR"
echo "Output dir: $OUTPUT_DIR"
echo ""

# Check prerequisites
if ! command -v ohrs &> /dev/null; then
    echo "ERROR: ohrs not found. Please install it:"
    echo "  cargo install ohrs"
    exit 1
fi

if [ -z "$OHOS_NDK_HOME" ]; then
    echo "WARNING: OHOS_NDK_HOME not set. Using default from ohrs."
fi

# Clean output directory
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Build targets - all supported architectures
TARGETS=(
    "aarch64-unknown-linux-ohos"
    "armv7-unknown-linux-ohos"
    "x86_64-unknown-linux-ohos"
)

# Map Rust targets to ohrs arch names
declare -A TARGET_MAP_OHRS=(
    ["aarch64-unknown-linux-ohos"]="arm64"
    ["armv7-unknown-linux-ohos"]="arm"
    ["x86_64-unknown-linux-ohos"]="x64"
)

# Map Rust targets to HarmonyOS ABI names
declare -A TARGET_MAP_OHOS=(
    ["aarch64-unknown-linux-ohos"]="arm64-v8a"
    ["armv7-unknown-linux-ohos"]="armeabi-v7a"
    ["x86_64-unknown-linux-ohos"]="x86_64"
)

cd "$PROJECT_DIR"

# Determine build profile
if [ "$BUILD_TYPE" = "release" ]; then
    PROFILE="release"
else
    PROFILE="dev"
fi

# Track build status
FAILED_TARGETS=()
SUCCESSFUL_TARGETS=()

for TARGET in "${TARGETS[@]}"; do
    echo "----------------------------------------"
    echo "Building for target: $TARGET"
    echo "----------------------------------------"
    
    OHRS_ARCH=${TARGET_MAP_OHRS["$TARGET"]}
    OHOS_ABI=${TARGET_MAP_OHOS["$TARGET"]}
    
    echo "OHRS arch: $OHRS_ARCH"
    echo "HarmonyOS ABI: $OHOS_ABI"
    
    # Check if target is installed
    if ! rustup target list --installed | grep -q "$TARGET"; then
        echo "WARNING: Target $TARGET not installed. Installing..."
        rustup target add "$TARGET" || {
            echo "ERROR: Failed to install target $TARGET"
            FAILED_TARGETS+=("$TARGET")
            continue
        }
    fi
    
    # Build using ohrs
    if [ "$BUILD_TYPE" = "release" ]; then
        if ohrs build --release --arch="$OHRS_ARCH"; then
            BUILD_SUCCESS=true
        else
            BUILD_SUCCESS=false
        fi
    else
        if ohrs build --arch="$OHRS_ARCH" --profile="$PROFILE"; then
            BUILD_SUCCESS=true
        else
            BUILD_SUCCESS=false
        fi
    fi
    
    if [ "$BUILD_SUCCESS" = false ]; then
        echo "ERROR: Build failed for $TARGET"
        FAILED_TARGETS+=("$TARGET")
        continue
    fi
    
    # Copy output
    mkdir -p "$OUTPUT_DIR/$OHOS_ABI"

    if [ "$BUILD_TYPE" = "release" ]; then
        LIB_PATH="$WORKSPACE_ROOT/target/$TARGET/release/libredis_ohos.so"
    else
        LIB_PATH="$WORKSPACE_ROOT/target/$TARGET/$PROFILE/libredis_ohos.so"
    fi

    if [ -f "$LIB_PATH" ]; then
        cp "$LIB_PATH" "$OUTPUT_DIR/$OHOS_ABI/"
        echo "✓ Built for $OHOS_ABI"
        SUCCESSFUL_TARGETS+=("$TARGET")
    else
        echo "ERROR: Library not found at $LIB_PATH"
        FAILED_TARGETS+=("$TARGET")
    fi
    
    echo ""
done

# Copy TypeScript definitions (generated by ohrs in dist/ directory)
echo "Copying TypeScript definitions..."
if [ -f "dist/index.d.ts" ]; then
    cp "dist/index.d.ts" "$OUTPUT_DIR/"
    echo "✓ Copied TypeScript definitions from dist/"
elif [ "$BUILD_TYPE" = "release" ]; then
    TARGET_DIR="$WORKSPACE_ROOT/target/aarch64-unknown-linux-ohos/release"
    if [ -f "$TARGET_DIR/index.d.ts" ]; then
        cp "$TARGET_DIR/index.d.ts" "$OUTPUT_DIR/"
        echo "✓ Copied TypeScript definitions from target/"
    fi
else
    TARGET_DIR="$WORKSPACE_ROOT/target/aarch64-unknown-linux-ohos/$PROFILE"
    if [ -f "$TARGET_DIR/index.d.ts" ]; then
        cp "$TARGET_DIR/index.d.ts" "$OUTPUT_DIR/"
        echo "✓ Copied TypeScript definitions from target/"
    fi
fi

# Create oh-package.json5
cat > "$OUTPUT_DIR/oh-package.json5" << 'EOF'
{
  "name": "libredis_ohos.so",
  "version": "1.0.0",
  "description": "Redis SDK for HarmonyOS - All Architectures",
  "main": "libredis_ohos.so",
  "author": "Liang"
}
EOF

echo "✓ Created oh-package.json5"
echo ""

echo "========================================="
echo "Build Summary"
echo "========================================="
echo ""

if [ ${#SUCCESSFUL_TARGETS[@]} -gt 0 ]; then
    echo "✓ Successful builds (${#SUCCESSFUL_TARGETS[@]}):"
    for TARGET in "${SUCCESSFUL_TARGETS[@]}"; do
        echo "  - $TARGET"
    done
    echo ""
fi

if [ ${#FAILED_TARGETS[@]} -gt 0 ]; then
    echo "✗ Failed builds (${#FAILED_TARGETS[@]}):"
    for TARGET in "${FAILED_TARGETS[@]}"; do
        echo "  - $TARGET"
    done
    echo ""
fi

if [ ${#SUCCESSFUL_TARGETS[@]} -gt 0 ]; then
    echo "Output directory: $OUTPUT_DIR"
    echo ""
    echo "Contents:"
    ls -lh "$OUTPUT_DIR"
    echo ""
    for ABI_DIR in "$OUTPUT_DIR"/*/; do
        if [ -d "$ABI_DIR" ]; then
            ABI_NAME=$(basename "$ABI_DIR")
            echo "$ABI_NAME:"
            ls -lh "$ABI_DIR"
            echo ""
        fi
    done
    
    echo "To use in your HarmonyOS project:"
    echo "1. Copy $OUTPUT_DIR/* to your project's entry/libs/Redis_sdk/"
    echo "2. Add dependency in entry/oh-package.json5:"
    echo '   "dependencies": {'
    echo '     "libredis_ohos.so": "file:./libs/Redis_sdk"'
    echo '   }'
fi

if [ ${#FAILED_TARGETS[@]} -gt 0 ]; then
    exit 1
fi

